version     = "1.5.1"
author      = "Andre von Houck"
description = "Puppy fetches HTML pages for Nim."
license     = "MIT"

requires "nim >= 1.4.4"
requires "urlly >= 0.2.0"
requires "libcurl >= 1.0.0"
requires "zippy >= 0.7.3"
requires "https://github.com/shayanhabibi/cooky >= 0.1.0"
